### PR TITLE
chore: upgrade to Jest 27

### PR DESCRIPTION
**Pull request by nickserv**
**What**: Upgrade to Jest 27

**Why**: Ensuring compatibility with breaking changes in Jest 27

**How**: Upgrading packages

### CODE REVIEW

**Comment by nickserv** [comment]
Do we want to fix these lint errors or disable the new ones and deal with it later?

**Comment by olivierwilkinson** [comment]
Hey, sorry for the slow response. I think fixing them would be good, I've been meaning to improve the type safety anyways so this is as good a time as any. I'll disable some and add a note if something proves difficult. :)

**Comment by nickserv** [comment]
I'm not sure why webdriverio is failing to connect though, any ideas? I ran a build on master (#25) and it succeeded.

**Comment by olivierwilkinson** [comment]
> I'm not sure why webdriverio is failing to connect though, any ideas? I ran a build on master (#25) and it succeeded.

I think what was happening is that the `validate` script exits because the `lint` command fails, so all the other processes get a SIGTERM which is what all that complaining by webdriverio is about haha.

I've fixed the eslint errors now and things seem to be working again so I hope it's something like that 😄

**Review by nickserv — COMMENTED** [review]
I'm not familiar with the inner workings of this library or Webdriverio, but this looks good, thanks!

**Comment by olivierwilkinson** [comment]
> I'm not familiar with the inner workings of this library or Webdriverio, but this looks good, thanks!

Awesome 😄  thanks for raising this btw, it prompted some positive changes! (And highlighted some areas that could still be improved 🙂)

**Review by olivierwilkinson — APPROVED** [review]

**Pull request merged**
