### PR TITLE
Compatibility for upcoming `v8`

### LINKED ISSUE #42: Compatibility with v8 of WebdriverIO
Hey 👋 

just wanted to let you know about a breaking change with the upcoming `v8` release. In there we remove all `browser` commands from element scopes. This breaks in `injectDOMTestingLibrary` where `container` is an element (with selector `'body'`). I suggest to call execute as follows `container.parent.execute(...)` to run the command from the browser scope. This would already work with today `v7` and prior versions.

Happy to provide a PR if needed.

### PR DESCRIPTION
**Pull request by christian-bromann**
fixes #42

### CODE REVIEW

**Comment by olivierwilkinson** [comment]
So the tests are only failing due to the Chrome version on the Ubuntu container being behind the latest Chromedriver version used by the selenium-standalone service. I've verified they pass locally and have fixed the build on main so I'm going to merge this. We use [semantic-release](https://github.com/semantic-release/semantic-release) so I need to update the commit format when I merge to trigger a release.

Thanks again for raising this. I'm really happy we now support v8, before it's released no less!

**Comment by christian-bromann** [comment]
Thanks for merging so quickly! I am currently working on a [component testing service](https://github.com/webdriverio-community/wdio-component-testing-service) for WebdriverIO and wanted to make sure folks can use this library too.

**Comment by olivierwilkinson** [comment]
> Thanks for merging so quickly!

No problem at all 😄

> I am currently working on a [component testing service](https://github.com/webdriverio-community/wdio-component-testing-service) for WebdriverIO and wanted to make sure folks can use this library too.

Oh that's an interesting project! Not having to spin up and navigate a whole app to get to the component in a real environment sounds awsome. Integration testing a complex component with jsdom is difficult or contrived sometimes for sure. Taking existing jsdom integration tests that use @testing-library/dom and translating them to use this library would be pretty easy too (but of course I would say that haha)

**Comment by christian-bromann** [comment]
Give it a whirl and raise issues if you have any feedback. Some things I have on my list before making an announcement is:

- fix support for react (currently the vite server chokes on rendering React components)
- support for DOM snapshots in expect-webdriverio
- mocking and stubbing functionlity, e.g. allow to pass in an onClose method as parameter and validate if it got called after certain interaction
- documentation, component testing guide, blog post

**Comment by olivierwilkinson** [comment]
> Give it a whirl and raise issues if you have any feedback.

Will do! 😁

**Pull request merged**
